name: Test Windows VM Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU for virtualization
      uses: docker/setup-qemu-action@v3
    
    - name: Ensure KVM is available (Optional)
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-kvm
        ls -la /dev/kvm

    - name: Start the Windows VM container
      # FIX: Changed 'docker-compose' to 'docker compose'
      run: |
        docker compose up --build -d
        echo "Docker Compose started in detached mode."
    
    - name: Wait for the container to initialize
      run: sleep 60
      
    - name: Check container status
      # FIX: Changed 'docker-compose' to 'docker compose'
      run: |
        docker compose ps
        docker logs windows

    - name: Stop and remove the container
      # FIX: Changed 'docker-compose' to 'docker compose'
      run: |
        docker compose down
        echo "Docker Compose services stopped and removed."
        
