version: '3.8'
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "ltsc"
      USERNAME: "MASTER"
      PASSWORD: "admin@123"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
      # FIX: Drastically reduced disk size to fit within the runner's storage.
      DISK_SIZE: "10G"
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
